{
  "name": "{{project.name}}",
  "version": "0.1.0",
  "private": true,
  "description": "{{project.description}}",
  "type": "module",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "start": "serve .output/public --config serve.json",
    "preview": "vite preview",
    "typecheck": "bun --bun fumadocs-mdx && tsc --noEmit",
    "lint": "oxlint",
    "lint:fix": "oxlint --fix",
    "format": "oxfmt --write .",
    "format:check": "oxfmt --check .",
    "lint:links": "linkinator .output/public --config linkinator.config.json",
    "check": "bun run typecheck && bun run lint && bun run format:check && bun run build",
    "postinstall": "bun --bun fumadocs-mdx",
    "copy-fonts": "bun scripts/copy-fonts.mjs",
    "predev": "bun run copy-fonts",
    "prebuild": "bun run copy-fonts"
  },
  "dependencies": {
    "@tanstack/react-router": "1.170.41",
    "@tanstack/react-start": "1.168.60",
    "@tanstack/start-static-server-functions": "1.167.39",
    "beautiful-mermaid": "^1.1.3",
    "fumadocs-core": "16.16.2",
    "fumadocs-mdx": "15.4.6",
    "fumadocs-ui": "16.16.2",
    "lucide-react": "^1.17.0",
    "react": "^19.2.6",
    "react-dom": "^19.2.6",
    "tailwind-merge": "^3.6.0"
  },
  "devDependencies": {
    "@tailwindcss/vite": "^4.3.0",
    "@types/bun": "1.4.2",
    "@types/hast": "^3.0.4",
    "@types/mdx": "2.0.13",
    "@types/node": "^25.9.1",
    "@types/react": "^19.2.15",
    "@types/react-dom": "^19.2.3",
    "@vitejs/plugin-react": "^6.0.2",
    "linkinator": "^6.1.2",
    "nitro": "3.0.260429-beta",
    "serve": "^14.2.6",
    "srvx": "^0.11.16",
    "tailwindcss": "^4.3.0",
    "vite": "^8.0.14"
  }
}
