# flake.module.nix — project-specific flake-parts customizations.
#
# seihou does NOT manage this file: it is never regenerated or overwritten by
# `seihou run` or module migrations, so it is the conflict-free home for every
# customization that must survive nix-haskell-flake template upgrades. See
# flake.module.nix.example (generated by the module) for the full option list.
#
# ┌──────────────────────────────────────────────────────────────────────────┐
# │ REQUIRED: this file MUST be git-tracked (`git add flake.module.nix`).      │
# │ Nix flakes evaluate only files tracked by git, so flake.nix's             │
# │ `builtins.pathExists ./flake.module.nix` import guard sees an untracked   │
# │ file as ABSENT and silently ignores everything below — no error, the      │
# │ customization just vanishes from the dev shell. After `git add`, prove it │
# │ took effect with `nix print-dev-env | grep <tool>`.                        │
# └──────────────────────────────────────────────────────────────────────────┘
{ inputs, ... }:
{
  perSystem = { pkgs, config, ... }: {
    # Extra dev-shell tools (conflict-free; reads the option declared in the
    # seihou-managed ./nix/haskell.nix). This is where inline additions that
    # used to live in `baseDevPackages` belong. Keep the explanatory comment.
    #
    #   # librdkafka: the C library hw-kafka-client / kafka-effectful link against.
    haskellProject.extraDevPackages = [ /* pkgs.rdkafka pkgs.just … */ ];

    # If the project defines its OWN default package build (e.g. a haskell-nix
    # overlay for patched private deps), set `nix.builtin-package = false` when
    # running the module so nix/haskell.nix does NOT also emit a
    # `packages.default` (two definitions collide → flake-parts eval error), and
    # define it here instead:
    #
    #   packages.default = (pkgs.haskell.packages.ghc9124.override { … }).my-package;
    #
    # With `nix.haskell-nix = true` the module owns a rev-pinned `inputs.haskell-nix`
    # (the shared patch registry — do NOT add it to flake.nix by hand). Compose its
    # extension ahead of your own overrides:
    #
    #   packages.default = (pkgs.haskell.packages.ghc9124.override {
    #     overrides = pkgs.lib.composeExtensions
    #       (inputs.haskell-nix.lib.haskellExtension pkgs.haskell.lib.compose pkgs)
    #       (hself: _hsuper: { my-package = hself.callCabal2nix "my-package" ./. { }; });
    #   }).my-package;

    # Override formatter details without editing the managed nix/treefmt.nix
    # (flake-parts merges treefmt.* options across modules):
    #
    #   treefmt.programs.fourmolu.package = pkgs.haskell.packages.ghc9124.fourmolu;
  };

  # A brand-new flake input must be added to flake.nix's top-level `inputs`
  # (a Nix requirement — inputs cannot be declared from an imported module).
  # That is the one edit that conflicts on a future migration; resolve it with
  # "accept new" and re-add the input line. (haskell-nix is module-owned — set
  # nix.haskell-nix = true instead of adding it here.)
  #
  # This file is only for flake-parts customizations. Two sibling unmanaged files
  # handle non-flake edits, and neither belongs here:
  #   • .envrc.local                  — custom direnv exports (gitignored; NOT git-added)
  #   • process-compose.override.yaml — extra process-compose processes (auto-merged)
}
