# UNMANAGED, project-specific build wiring. This file is never regenerated by a
# template upgrade — it is the one place to evolve the package build and any
# custom checks. It is imported only when present (see the `builtins.pathExists`
# guard in flake.nix), so a pure library that needs no package output may omit it
# entirely.
#
# ---------------------------------------------------------------------------
# VARIANT A — project HAS a haskell-nix overlay (Tier A, and Tier B projects
# that carry their own nix/haskell-overlay.nix). Build from a ghc9124 package
# set extended with two composed overlays: the shared haskell-nix registry
# (patch management) composed with the project's ./nix/haskell-overlay.nix.
# ---------------------------------------------------------------------------
{ inputs, ... }:
{
  perSystem = { system, pkgs, ... }:
    let
      gitRev = inputs.self.shortRev or "dirty";

      haskellPackages = pkgs.haskell.packages.ghc9124.override {
        overrides = pkgs.lib.composeExtensions
          (inputs.haskell-nix.lib.haskellExtension pkgs.haskell.lib.compose pkgs)
          (import ./nix/haskell-overlay.nix {
            inherit pkgs gitRev;
            # Pass through any non-flake source inputs the overlay consumes, e.g.:
            # some-src = inputs.some-src;
          });
      };
    in
    {
      packages.<name> = haskellPackages.<haskell-attr>;
      packages.default = haskellPackages.<haskell-attr>;

      # Any custom flake checks the project had go here too, e.g. a runCommand
      # that mirrors a pre-commit hook:
      # checks.cli-module-placement = pkgs.runCommand "cli-module-placement-check"
      #   { src = inputs.self; nativeBuildInputs = [ pkgs.bash ]; }
      #   ''
      #     cp -r $src ./repo; chmod -R u+w ./repo; cd ./repo
      #     bash nix/check-cli-module-placement.sh
      #     touch $out
      #   '';
    };
}

# ---------------------------------------------------------------------------
# VARIANT B — Tier B project with NO overlay. Build the package directly from
# the ghc9124 set with callCabal2nix and drop the haskell-nix input:
#
# { inputs, ... }:
# {
#   perSystem = { pkgs, ... }:
#     {
#       packages.default =
#         pkgs.haskell.packages.ghc9124.callCabal2nix "<name>" inputs.self { };
#     };
# }
# ---------------------------------------------------------------------------
